In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import datetime

In [ ]:
def merge_csv_files(directory_path):
    """
    Merges all CSV files in a directory into a single pandas DataFrame.
    
    Args:
    directory_path (str): The directory path containing the CSV files.
    
    Returns:
    merged_df (pandas.DataFrame): The merged pandas DataFrame of all CSV files in the directory.
    """
    dfs = []

    # loop through each file in the directory
    for file in os.listdir(directory_path):
        # check if the file is a CSV file
        if file.endswith('.csv'):
            file_path = os.path.join(directory_path, file)
            if directory_path.endswith("dataverse_file"):
                df = pd.read_csv(file_path, delimiter=",")
            else:
                df = pd.read_csv(file_path, delimiter=";")
            dfs.append(df)

    # concatenate all dataframes 
    merged_df = pd.concat(dfs, ignore_index=True)

    return merged_df

In [ ]:
# Noise data

folder_path = '/content/drive/MyDrive/MDA_TIEN'

file40 = merge_csv_files(folder_path + '/export_40')
file41 = merge_csv_files(folder_path + '/export_41')
file42 = merge_csv_files(folder_path + '/export_42')

## file 41 - noise event

In [ ]:
file41.head(10)

,#object_id,description,result_timestamp,noise_event_laeq_model_id,noise_event_laeq_model_id_unit,noise_event_laeq_primary_detected_certainty,noise_event_laeq_primary_detected_certainty_unit,noise_event_laeq_primary_detected_class,noise_event_laeq_primary_detected_class_unit
0,255440,MP 02: Naamsestraat 57 Xior,01/03/2022 03:52:12.714,NaN,NaN,NaN,%,NaN,NaN
1,255440,MP 02: Naamsestraat 57 Xior,01/03/2022 05:07:17.712,NaN,NaN,NaN,%,NaN,NaN
2,255440,MP 02: Naamsestraat 57 Xior,01/03/2022 05:07:34.711,NaN,NaN,NaN,%,NaN,NaN
3,255440,MP 02: Naamsestraat 57 Xior,01/03/2022 08:28:22.694,NaN,NaN,NaN,%,NaN,NaN
4,255440,MP 02: Naamsestraat 57 Xior,01/03/2022 08:38:59.695,NaN,NaN,NaN,%,NaN,NaN
5,255440,MP 02: Naamsestraat 57 Xior,01/03/2022 10:25:58.687,NaN,NaN,NaN,%,NaN,NaN
6,255440,MP 02: Naamsestraat 57 Xior,01/03/2022 11:17:29.681,NaN,NaN,NaN,%,NaN,NaN
7,255440,MP 02: Naamsestraat 57 Xior,01/03/2022 11:51:50.679,NaN,NaN,NaN,%,NaN,NaN
8,255440,MP 02: Naamsestraat 57 Xior,01/03/2022 12:27:57.676,NaN,NaN,NaN,%,NaN,NaN
9,255440,MP 02: Naamsestraat 57 Xior,01/03/2022 14:45:54.669,NaN,NaN,NaN,%,NaN,NaN

In [ ]:
file41.shape

(81056, 9)

In [ ]:
# check missing values
file41.isna().mean()

#object_id                                          0.000000
description                                         0.000000
result_timestamp                                    0.000000
noise_event_laeq_model_id                           0.047153
noise_event_laeq_model_id_unit                      1.000000
noise_event_laeq_primary_detected_certainty         0.047153
noise_event_laeq_primary_detected_certainty_unit    0.000000
noise_event_laeq_primary_detected_class             0.047153
noise_event_laeq_primary_detected_class_unit        1.000000
dtype: float64

In [ ]:
file41.loc[~file41["noise_event_laeq_model_id"].isnull()].head(10)

,#object_id,description,result_timestamp,noise_event_laeq_model_id,noise_event_laeq_model_id_unit,noise_event_laeq_primary_detected_certainty,noise_event_laeq_primary_detected_certainty_unit,noise_event_laeq_primary_detected_class,noise_event_laeq_primary_detected_class_unit
94,255440,MP 02: Naamsestraat 57 Xior,07/03/2022 22:22:41.166,13.0,NaN,75.0,%,Transport road - Passenger car,NaN
95,255440,MP 02: Naamsestraat 57 Xior,08/03/2022 01:25:51.161,13.0,NaN,75.0,%,Transport road - Siren,NaN
96,255440,MP 02: Naamsestraat 57 Xior,08/03/2022 07:20:38.135,13.0,NaN,98.0,%,Transport road - Passenger car,NaN
97,255440,MP 02: Naamsestraat 57 Xior,08/03/2022 08:37:44.126,13.0,NaN,81.0,%,Transport road - Passenger car,NaN
98,255440,MP 02: Naamsestraat 57 Xior,08/03/2022 08:48:07.124,13.0,NaN,87.0,%,Transport road - Passenger car,NaN
99,255440,MP 02: Naamsestraat 57 Xior,08/03/2022 09:07:24.122,13.0,NaN,66.0,%,Transport road - Siren,NaN
100,255440,MP 02: Naamsestraat 57 Xior,08/03/2022 10:07:33.120,13.0,NaN,92.0,%,Transport road - Passenger car,NaN
101,255440,MP 02: Naamsestraat 57 Xior,08/03/2022 10:22:33.120,13.0,NaN,87.0,%,Transport road - Passenger car,NaN
102,255440,MP 02: Naamsestraat 57 Xior,08/03/2022 11:59:55.114,13.0,NaN,48.0,%,Transport road - Passenger car,NaN
103,255440,MP 02: Naamsestraat 57 Xior,08/03/2022 14:24:40.110,13.0,NaN,47.0,%,Transport road - Siren,NaN

In [ ]:
# drop unncessary cols
cols_to_drop = ["noise_event_laeq_model_id_unit", "noise_event_laeq_model_id", 
                "noise_event_laeq_primary_detected_certainty_unit", 
                "noise_event_laeq_primary_detected_class_unit"]

file41.drop(cols_to_drop, axis=1, inplace=True)

In [ ]:
# rename cols 
file41.columns = ['object_id', 'location', 'result_timestamp', "noise_event_certainty", "noise_event"]
file41.tail(5)

,object_id,location,result_timestamp,noise_event_certainty,noise_event
81051,280324,MP08bis - Vrijthof,29/12/2022 09:08:11.171,99.0,Human voice - Shouting
81052,280324,MP08bis - Vrijthof,30/12/2022 13:54:27.224,99.0,Nature elements - Wind
81053,280324,MP08bis - Vrijthof,30/12/2022 13:56:57.225,0.0,Unsupported
81054,280324,MP08bis - Vrijthof,30/12/2022 15:09:33.233,100.0,Nature elements - Wind
81055,280324,MP08bis - Vrijthof,31/12/2022 12:01:26.480,100.0,Nature elements - Wind

In [ ]:
## remove the noise_event that are unsupported
file41 = file41.loc[file41.noise_event != "Unsupported"]

In [ ]:
file41.shape

(60265, 5)

In [ ]:
file41.groupby(["object_id", "noise_event"]).count()

                                          location  result_timestamp  \
object_id noise_event
255439    Human voice - Shouting              2470              2470
          Human voice - Singing                239               239
          Music non-amplified                    2                 2
          Nature elements - Wind                17                17
          Transport road - Passenger car     15402             15402
          Transport road - Siren               118               118
255440    Human voice - Shouting               424               424
          Human voice - Singing                 43                43
          Music non-amplified                    4                 4
          Nature elements - Wind                 9                 9
          Transport road - Passenger car      2098              2098
          Transport road - Siren               231               231
255441    Human voice - Shouting               666               666
          Human voice - Singing                 27                27
          Music non-amplified                    1                 1
          Nature elements - Wind                20                20
          Transport road - Passenger car      4206              4206
          Transport road - Siren               332               332
255442    Human voice - Shouting               864               864
          Human voice - Singing                  7                 7
          Music non-amplified                   75                75
          Nature elements - Wind                 3                 3
          Transport road - Passenger car      5471              5471
          Transport road - Siren               354               354
255443    Human voice - Shouting               547               547
          Human voice - Singing                115               115
          Music non-amplified                    6                 6
          Nature elements - Wind                19                19
          Transport road - Passenger car      5646              5646
          Transport road - Siren               388               388
255444    Human voice - Shouting               493               493
          Human voice - Singing                532               532
          Music non-amplified                    3                 3
          Nature elements - Wind                21                21
          Transport road - Passenger car     14175             14175
          Transport road - Siren               431               431
280324    Human voice - Shouting                16                16
          Human voice - Singing                119               119
          Nature elements - Wind                10                10
          Transport road - Passenger car        17                17
          Transport road - Siren                36                36

                                          noise_event_certainty
object_id noise_event
255439    Human voice - Shouting                           2470
          Human voice - Singing                             239
          Music non-amplified                                 2
          Nature elements - Wind                             17
          Transport road - Passenger car                  15402
          Transport road - Siren                            118
255440    Human voice - Shouting                            424
          Human voice - Singing                              43
          Music non-amplified                                 4
          Nature elements - Wind                              9
          Transport road - Passenger car                   2098
          Transport road - Siren                            231
255441    Human voice - Shouting                            666
          Human voice - Singing                              27
          Music non-amplified                                 1
          Nature elements - Wind                             20
          Transport road - Passenger car                   4206
          Transport road - Siren                            332
255442    Human voice - Shouting                            864
          Human voice - Singing                               7
          Music non-amplified                                75
          Nature elements - Wind                              3
          Transport road - Passenger car                   5471
          Transport road - Siren                            354
255443    Human voice - Shouting                            547
          Human voice - Singing                             115
          Music non-amplified                                 6
          Nature elements - Wind                             19
          Transport road - Passenger car                   5646
          Transport road - Siren                            388
255444    Human voice - Shouting                            493
          Human voice - Singing                             532
          Music non-amplified                                 3
          Nature elements - Wind                             21
          Transport road - Passenger car                  14175
          Transport road - Siren                            431
280324    Human voice - Shouting                             16
          Human voice - Singing                             119
          Nature elements - Wind                             10
          Transport road - Passenger car                     17
          Transport road - Siren                             36

In [ ]:
pd.to_datetime(file41['result_timestamp']).dt.date

94       2022-07-03
95       2022-08-03
96       2022-08-03
97       2022-08-03
98       2022-08-03
            ...
81047    2022-12-28
81051    2022-12-29
81052    2022-12-30
81054    2022-12-30
81055    2022-12-31
Name: result_timestamp, Length: 55657, dtype: object

In [ ]:
# extract from timestamp
file41["result_timestamp"] = pd.to_datetime(file41['result_timestamp'])
file41['time'] = file41['result_timestamp'].dt.time
file41['date'] = file41['result_timestamp'].dt.date
file41['hour'] = file41['result_timestamp'].dt.hour
file41["month"] = file41["result_timestamp"].dt.month
file41['weekday'] = file41['result_timestamp'].dt.strftime('%a')
file41.head(10)

,object_id,location,result_timestamp,noise_event_certainty,noise_event,time,date,hour,month,weekday
0,255440,MP 02: Naamsestraat 57 Xior,2022-01-03 03:52:12.714,NaN,NaN,03:52:12.714000,2022-01-03,3,1,Mon
1,255440,MP 02: Naamsestraat 57 Xior,2022-01-03 05:07:17.712,NaN,NaN,05:07:17.712000,2022-01-03,5,1,Mon
2,255440,MP 02: Naamsestraat 57 Xior,2022-01-03 05:07:34.711,NaN,NaN,05:07:34.711000,2022-01-03,5,1,Mon
3,255440,MP 02: Naamsestraat 57 Xior,2022-01-03 08:28:22.694,NaN,NaN,08:28:22.694000,2022-01-03,8,1,Mon
4,255440,MP 02: Naamsestraat 57 Xior,2022-01-03 08:38:59.695,NaN,NaN,08:38:59.695000,2022-01-03,8,1,Mon
5,255440,MP 02: Naamsestraat 57 Xior,2022-01-03 10:25:58.687,NaN,NaN,10:25:58.687000,2022-01-03,10,1,Mon
6,255440,MP 02: Naamsestraat 57 Xior,2022-01-03 11:17:29.681,NaN,NaN,11:17:29.681000,2022-01-03,11,1,Mon
7,255440,MP 02: Naamsestraat 57 Xior,2022-01-03 11:51:50.679,NaN,NaN,11:51:50.679000,2022-01-03,11,1,Mon
8,255440,MP 02: Naamsestraat 57 Xior,2022-01-03 12:27:57.676,NaN,NaN,12:27:57.676000,2022-01-03,12,1,Mon
9,255440,MP 02: Naamsestraat 57 Xior,2022-01-03 14:45:54.669,NaN,NaN,14:45:54.669000,2022-01-03,14,1,Mon

In [ ]:
np.unique(file41.object_id)

array([255439, 255440, 255441, 255442, 255443, 255444, 280324],
      dtype=object)

In [ ]:
np.unique(file41.date)

array([datetime.date(2022, 1, 2), datetime.date(2022, 1, 3),
       datetime.date(2022, 1, 4), datetime.date(2022, 1, 5),
       datetime.date(2022, 1, 6), datetime.date(2022, 1, 7),
       datetime.date(2022, 1, 8), datetime.date(2022, 1, 9),
       datetime.date(2022, 1, 10), datetime.date(2022, 1, 11),
       datetime.date(2022, 1, 12), datetime.date(2022, 1, 13),
       datetime.date(2022, 1, 14), datetime.date(2022, 1, 15),
       datetime.date(2022, 1, 16), datetime.date(2022, 1, 17),
       datetime.date(2022, 1, 18), datetime.date(2022, 1, 19),
       datetime.date(2022, 1, 20), datetime.date(2022, 1, 21),
       datetime.date(2022, 1, 22), datetime.date(2022, 1, 23),
       datetime.date(2022, 1, 24), datetime.date(2022, 1, 25),
       datetime.date(2022, 1, 26), datetime.date(2022, 1, 27),
       datetime.date(2022, 1, 28), datetime.date(2022, 1, 29),
       datetime.date(2022, 1, 30), datetime.date(2022, 1, 31),
       datetime.date(2022, 2, 2), datetime.date(2022, 2, 3),
       datetime.date(2022, 2, 4), datetime.date(2022, 2, 5),
       datetime.date(2022, 2, 6), datetime.date(2022, 2, 7),
       datetime.date(2022, 2, 8), datetime.date(2022, 2, 9),
       datetime.date(2022, 2, 10), datetime.date(2022, 2, 11),
       datetime.date(2022, 2, 12), datetime.date(2022, 2, 13),
       datetime.date(2022, 2, 14), datetime.date(2022, 2, 15),
       datetime.date(2022, 2, 16), datetime.date(2022, 2, 17),
       datetime.date(2022, 2, 18), datetime.date(2022, 2, 19),
       datetime.date(2022, 2, 20), datetime.date(2022, 2, 21),
       datetime.date(2022, 2, 22), datetime.date(2022, 2, 23),
       datetime.date(2022, 2, 24), datetime.date(2022, 2, 25),
       datetime.date(2022, 2, 26), datetime.date(2022, 2, 27),
       datetime.date(2022, 2, 28), datetime.date(2022, 3, 2),
       datetime.date(2022, 3, 3), datetime.date(2022, 3, 4),
       datetime.date(2022, 3, 5), datetime.date(2022, 3, 6),
       datetime.date(2022, 3, 7), datetime.date(2022, 3, 8),
       datetime.date(2022, 3, 9), datetime.date(2022, 3, 10),
       datetime.date(2022, 3, 11), datetime.date(2022, 3, 12),
       datetime.date(2022, 3, 13), datetime.date(2022, 3, 14),
       datetime.date(2022, 3, 15), datetime.date(2022, 3, 16),
       datetime.date(2022, 3, 17), datetime.date(2022, 3, 18),
       datetime.date(2022, 3, 19), datetime.date(2022, 3, 20),
       datetime.date(2022, 3, 21), datetime.date(2022, 3, 22),
       datetime.date(2022, 3, 23), datetime.date(2022, 3, 24),
       datetime.date(2022, 3, 25), datetime.date(2022, 3, 26),
       datetime.date(2022, 3, 27), datetime.date(2022, 3, 28),
       datetime.date(2022, 3, 29), datetime.date(2022, 3, 30),
       datetime.date(2022, 3, 31), datetime.date(2022, 4, 2),
       datetime.date(2022, 4, 3), datetime.date(2022, 4, 4),
       datetime.date(2022, 4, 5), datetime.date(2022, 4, 6),
       datetime.date(2022, 4, 7), datetime.date(2022, 4, 8),
       datetime.date(2022, 4, 9), datetime.date(2022, 4, 10),
       datetime.date(2022, 4, 11), datetime.date(2022, 4, 12),
       datetime.date(2022, 4, 13), datetime.date(2022, 4, 14),
       datetime.date(2022, 4, 15), datetime.date(2022, 4, 16),
       datetime.date(2022, 4, 17), datetime.date(2022, 4, 18),
       datetime.date(2022, 4, 19), datetime.date(2022, 4, 20),
       datetime.date(2022, 4, 21), datetime.date(2022, 4, 22),
       datetime.date(2022, 4, 23), datetime.date(2022, 4, 24),
       datetime.date(2022, 4, 25), datetime.date(2022, 4, 26),
       datetime.date(2022, 4, 27), datetime.date(2022, 4, 28),
       datetime.date(2022, 4, 29), datetime.date(2022, 4, 30),
       datetime.date(2022, 5, 2), datetime.date(2022, 5, 3),
       datetime.date(2022, 5, 4), datetime.date(2022, 5, 5),
       datetime.date(2022, 5, 6), datetime.date(2022, 5, 7),
       datetime.date(2022, 5, 8), datetime.date(2022, 5, 9),
       datetime.date(2022, 5, 10), datetime.date(2022, 5, 11),
       datetime.date(2022, 5, 12), datetime.date(2022, 5, 13),
       datetime.date(2022, 5, 14), datetime.date(2022, 5, 15),
       datetime.date(2022, 5, 16), datetime.date(2022, 5, 17),
       datetime.date(2022, 5, 18), datetime.date(2022, 5, 19),
       datetime.date(2022, 5, 20), datetime.date(2022, 5, 21),
       datetime.date(2022, 5, 22), datetime.date(2022, 5, 23),
       datetime.date(2022, 5, 24), datetime.date(2022, 5, 25),
       datetime.date(2022, 5, 26), datetime.date(2022, 5, 27),
       datetime.date(2022, 5, 28), datetime.date(2022, 5, 29),
       datetime.date(2022, 5, 30), datetime.date(2022, 5, 31),
       datetime.date(2022, 6, 2), datetime.date(2022, 6, 3),
       datetime.date(2022, 6, 4), datetime.date(2022, 6, 5),
       datetime.date(2022, 6, 6), datetime.date(2022, 6, 7),
       datetime.date(2022, 6, 8), datetime.date(2022, 6, 9),
       datetime.date(2022, 6, 10), datetime.date(2022, 6, 11),
       datetime.date(2022, 6, 12), datetime.date(2022, 6, 13),
       datetime.date(2022, 6, 14), datetime.date(2022, 6, 15),
       datetime.date(2022, 6, 16), datetime.date(2022, 6, 17),
       datetime.date(2022, 6, 18), datetime.date(2022, 6, 19),
       datetime.date(2022, 6, 20), datetime.date(2022, 6, 21),
       datetime.date(2022, 6, 22), datetime.date(2022, 6, 23),
       datetime.date(2022, 6, 24), datetime.date(2022, 6, 25),
       datetime.date(2022, 6, 26), datetime.date(2022, 6, 27),
       datetime.date(2022, 6, 28), datetime.date(2022, 6, 29),
       datetime.date(2022, 6, 30), datetime.date(2022, 7, 1),
       datetime.date(2022, 7, 2), datetime.date(2022, 7, 3),
       datetime.date(2022, 7, 4), datetime.date(2022, 7, 5),
       datetime.date(2022, 7, 6), datetime.date(2022, 7, 7),
       datetime.date(2022, 7, 8), datetime.date(2022, 7, 9),
       datetime.date(2022, 7, 10), datetime.date(2022, 7, 11),
       datetime.date(2022, 7, 12), datetime.date(2022, 7, 13),
       datetime.date(2022, 7, 14), datetime.date(2022, 7, 15),
       datetime.date(2022, 7, 16), datetime.date(2022, 7, 17),
       datetime.date(2022, 7, 18), datetime.date(2022, 7, 19),
       datetime.date(2022, 7, 20), datetime.date(2022, 7, 21),
       datetime.date(2022, 7, 22), datetime.date(2022, 7, 23),
       datetime.date(2022, 7, 24), datetime.date(2022, 7, 25),
       datetime.date(2022, 7, 26), datetime.date(2022, 7, 27),
       datetime.date(2022, 7, 28), datetime.date(2022, 7, 29),
       datetime.date(2022, 7, 30), datetime.date(2022, 7, 31),
       datetime.date(2022, 8, 1), datetime.date(2022, 8, 2),
       datetime.date(2022, 8, 3), datetime.date(2022, 8, 4),
       datetime.date(2022, 8, 5), datetime.date(2022, 8, 6),
       datetime.date(2022, 8, 7), datetime.date(2022, 8, 8),
       datetime.date(2022, 8, 9), datetime.date(2022, 8, 10),
       datetime.date(2022, 8, 11), datetime.date(2022, 8, 12),
       datetime.date(2022, 8, 13), datetime.date(2022, 8, 14),
       datetime.date(2022, 8, 15), datetime.date(2022, 8, 16),
       datetime.date(2022, 8, 17), datetime.date(2022, 8, 18),
       datetime.date(2022, 8, 19), datetime.date(2022, 8, 20),
       datetime.date(2022, 8, 21), datetime.date(2022, 8, 22),
       datetime.date(2022, 8, 23), datetime.date(2022, 8, 24),
       datetime.date(2022, 8, 25), datetime.date(2022, 8, 26),
       datetime.date(2022, 8, 27), datetime.date(2022, 8, 28),
       datetime.date(2022, 8, 29), datetime.date(2022, 8, 30),
       datetime.date(2022, 8, 31), datetime.date(2022, 9, 1),
       datetime.date(2022, 9, 2), datetime.date(2022, 9, 3),
       datetime.date(2022, 9, 4), datetime.date(2022, 9, 5),
       datetime.date(2022, 9, 6), datetime.date(2022, 9, 7),
       datetime.date(2022, 9, 8), datetime.date(2022, 9, 9),
       datetime.date(2022, 9, 10), datetime.date(2022, 9, 11),
       datetime.date(2022, 9, 12), datetime.date(2022, 9, 13),
       datetime.date(2022, 9, 14), datetime.date(2022, 9, 15),
       datetime.date(2022, 9, 16), datetime.date(2022, 9, 17),
       datetime.date(2022, 9, 18), datetime.date(2022, 9, 19),
       datetime.date(2022, 9, 20), datetime.date(2022, 9, 21),
       datetime.date(2022, 9, 22), datetime.date(2022, 9, 23),
       datetime.date(2022, 9, 24), datetime.date(2022, 9, 25),
       datetime.date(2022, 9, 26), datetime.date(2022, 9, 27),
       datetime.date(2022, 9, 28), datetime.date(2022, 9, 29),
       datetime.date(2022, 9, 30), datetime.date(2022, 10, 1),
       datetime.date(2022, 10, 2), datetime.date(2022, 10, 3),
       datetime.date(2022, 10, 4), datetime.date(2022, 10, 5),
       datetime.date(2022, 10, 6), datetime.date(2022, 10, 7),
       datetime.date(2022, 10, 8), datetime.date(2022, 10, 9),
       datetime.date(2022, 10, 10), datetime.date(2022, 10, 11),
       datetime.date(2022, 10, 12), datetime.date(2022, 10, 13),
       datetime.date(2022, 10, 14), datetime.date(2022, 10, 15),
       datetime.date(2022, 10, 16), datetime.date(2022, 10, 17),
       datetime.date(2022, 10, 18), datetime.date(2022, 10, 19),
       datetime.date(2022, 10, 20), datetime.date(2022, 10, 21),
       datetime.date(2022, 10, 22), datetime.date(2022, 10, 23),
       datetime.date(2022, 10, 24), datetime.date(2022, 10, 25),
       datetime.date(2022, 10, 26), datetime.date(2022, 10, 27),
       datetime.date(2022, 10, 28), datetime.date(2022, 10, 29),
       datetime.date(2022, 10, 30), datetime.date(2022, 10, 31),
       datetime.date(2022, 11, 1), datetime.date(2022, 11, 2),
       datetime.date(2022, 11, 3), datetime.date(2022, 11, 4),
       datetime.date(2022, 11, 5), datetime.date(2022, 11, 6),
       datetime.date(2022, 11, 7), datetime.date(2022, 11, 8),
       datetime.date(2022, 11, 9), datetime.date(2022, 11, 10),
       datetime.date(2022, 11, 11), datetime.date(2022, 11, 12),
       datetime.date(2022, 11, 13), datetime.date(2022, 11, 14),
       datetime.date(2022, 11, 15), datetime.date(2022, 11, 16),
       datetime.date(2022, 11, 17), datetime.date(2022, 11, 18),
       datetime.date(2022, 11, 19), datetime.date(2022, 11, 20),
       datetime.date(2022, 11, 21), datetime.date(2022, 11, 22),
       datetime.date(2022, 11, 23), datetime.date(2022, 11, 24),
       datetime.date(2022, 11, 25), datetime.date(2022, 11, 26),
       datetime.date(2022, 11, 27), datetime.date(2022, 11, 28),
       datetime.date(2022, 11, 29), datetime.date(2022, 11, 30),
       datetime.date(2022, 12, 1), datetime.date(2022, 12, 2),
       datetime.date(2022, 12, 3), datetime.date(2022, 12, 4),
       datetime.date(2022, 12, 5), datetime.date(2022, 12, 6),
       datetime.date(2022, 12, 7), datetime.date(2022, 12, 8),
       datetime.date(2022, 12, 9), datetime.date(2022, 12, 10),
       datetime.date(2022, 12, 11), datetime.date(2022, 12, 12),
       datetime.date(2022, 12, 13), datetime.date(2022, 12, 14),
       datetime.date(2022, 12, 15), datetime.date(2022, 12, 16),
       datetime.date(2022, 12, 17), datetime.date(2022, 12, 18),
       datetime.date(2022, 12, 19), datetime.date(2022, 12, 20),
       datetime.date(2022, 12, 21), datetime.date(2022, 12, 22),
       datetime.date(2022, 12, 23), datetime.date(2022, 12, 24),
       datetime.date(2022, 12, 25), datetime.date(2022, 12, 26),
       datetime.date(2022, 12, 27), datetime.date(2022, 12, 28),
       datetime.date(2022, 12, 29), datetime.date(2022, 12, 30),
       datetime.date(2022, 12, 31)], dtype=object)

## File 40  - Noise percentile

In [ ]:
file40.head(10)

,#object_id,description,result_timestamp,laf005_per_hour,laf005_per_hour_unit,laf01_per_hour,laf01_per_hour_unit,laf05_per_hour,laf05_per_hour_unit,laf10_per_hour,...,laf90_per_hour,laf90_per_hour_unit,laf95_per_hour,laf95_per_hour_unit,laf98_per_hour,laf98_per_hour_unit,laf99_per_hour,laf99_per_hour_unit,laf995_per_hour,laf995_per_hour_unit
0,303910,MP 04: His & Hears,16/10/2022 17:00:00.000,77.6,dB(A),75.7,dB(A),70.6,dB(A),65.2,...,31.3,dB(A),31.0,dB(A),30.8,dB(A),30.7,dB(A),30.6,dB(A)
1,303910,MP 04: His & Hears,16/10/2022 18:00:00.000,49.5,dB(A),47.3,dB(A),42.1,dB(A),39.1,...,30.8,dB(A),30.6,dB(A),30.5,dB(A),30.4,dB(A),30.4,dB(A)
2,303910,MP 04: His & Hears,16/10/2022 19:00:00.000,59.5,dB(A),57.1,dB(A),49.9,dB(A),44.8,...,31.4,dB(A),31.1,dB(A),30.8,dB(A),30.7,dB(A),30.6,dB(A)
3,303910,MP 04: His & Hears,16/10/2022 20:00:00.000,45.4,dB(A),43.1,dB(A),39.6,dB(A),38.3,...,30.8,dB(A),30.7,dB(A),30.6,dB(A),30.5,dB(A),30.5,dB(A)
4,303910,MP 04: His & Hears,16/10/2022 21:00:00.000,42.6,dB(A),40.4,dB(A),36.2,dB(A),34.3,...,30.7,dB(A),30.6,dB(A),30.5,dB(A),30.5,dB(A),30.4,dB(A)
5,303910,MP 04: His & Hears,16/10/2022 22:00:00.000,41.7,dB(A),39.5,dB(A),36.0,dB(A),34.1,...,30.7,dB(A),30.6,dB(A),30.5,dB(A),30.5,dB(A),30.4,dB(A)
6,303910,MP 04: His & Hears,16/10/2022 23:00:00.000,37.6,dB(A),35.7,dB(A),33.1,dB(A),31.7,...,30.6,dB(A),30.5,dB(A),30.4,dB(A),30.4,dB(A),30.4,dB(A)
7,303910,MP 04: His & Hears,17/10/2022 00:00:00.000,35.7,dB(A),35.3,dB(A),32.6,dB(A),31.5,...,30.6,dB(A),30.6,dB(A),30.5,dB(A),30.5,dB(A),30.4,dB(A)
8,303910,MP 04: His & Hears,17/10/2022 01:00:00.000,35.8,dB(A),35.3,dB(A),32.6,dB(A),31.6,...,30.7,dB(A),30.6,dB(A),30.6,dB(A),30.5,dB(A),30.5,dB(A)
9,303910,MP 04: His & Hears,17/10/2022 02:00:00.000,35.7,dB(A),35.2,dB(A),32.4,dB(A),31.5,...,30.7,dB(A),30.6,dB(A),30.5,dB(A),30.5,dB(A),30.4,dB(A)

In [ ]:
file40.isna().mean()

#object_id              0.0
description             0.0
result_timestamp        0.0
laf005_per_hour         0.0
laf005_per_hour_unit    0.0
laf01_per_hour          0.0
laf01_per_hour_unit     0.0
laf05_per_hour          0.0
laf05_per_hour_unit     0.0
laf10_per_hour          0.0
laf10_per_hour_unit     0.0
laf25_per_hour          0.0
laf25_per_hour_unit     0.0
laf50_per_hour          0.0
laf50_per_hour_unit     0.0
laf75_per_hour          0.0
laf75_per_hour_unit     0.0
laf90_per_hour          0.0
laf90_per_hour_unit     0.0
laf95_per_hour          0.0
laf95_per_hour_unit     0.0
laf98_per_hour          0.0
laf98_per_hour_unit     0.0
laf99_per_hour          0.0
laf99_per_hour_unit     0.0
laf995_per_hour         0.0
laf995_per_hour_unit    0.0
dtype: float64

In [ ]:
### we would delete unit column because of same values
# drop all _unit columns
cols_to_drop  = [col for col in file40.columns if col.endswith('unit')]
file40.drop(cols_to_drop, axis=1, inplace=True)

# rename columns
file40.rename(columns={'description':'location',
                       "#object_id": "object_id"}, inplace=True)

In [ ]:
file40.head(10)

,object_id,location,result_timestamp,laf005_per_hour,laf01_per_hour,laf05_per_hour,laf10_per_hour,laf25_per_hour,laf50_per_hour,laf75_per_hour,laf90_per_hour,laf95_per_hour,laf98_per_hour,laf99_per_hour,laf995_per_hour
0,303910,MP 04: His & Hears,16/10/2022 17:00:00.000,77.6,75.7,70.6,65.2,43.7,35.6,32.1,31.3,31.0,30.8,30.7,30.6
1,303910,MP 04: His & Hears,16/10/2022 18:00:00.000,49.5,47.3,42.1,39.1,34.8,32.4,31.2,30.8,30.6,30.5,30.4,30.4
2,303910,MP 04: His & Hears,16/10/2022 19:00:00.000,59.5,57.1,49.9,44.8,38.4,33.8,32.2,31.4,31.1,30.8,30.7,30.6
3,303910,MP 04: His & Hears,16/10/2022 20:00:00.000,45.4,43.1,39.6,38.3,35.6,32.1,31.1,30.8,30.7,30.6,30.5,30.5
4,303910,MP 04: His & Hears,16/10/2022 21:00:00.000,42.6,40.4,36.2,34.3,31.9,31.2,30.9,30.7,30.6,30.5,30.5,30.4
5,303910,MP 04: His & Hears,16/10/2022 22:00:00.000,41.7,39.5,36.0,34.1,31.8,31.2,30.9,30.7,30.6,30.5,30.5,30.4
6,303910,MP 04: His & Hears,16/10/2022 23:00:00.000,37.6,35.7,33.1,31.7,31.2,31.0,30.8,30.6,30.5,30.4,30.4,30.4
7,303910,MP 04: His & Hears,17/10/2022 00:00:00.000,35.7,35.3,32.6,31.5,31.2,31.0,30.8,30.6,30.6,30.5,30.5,30.4
8,303910,MP 04: His & Hears,17/10/2022 01:00:00.000,35.8,35.3,32.6,31.6,31.3,31.0,30.8,30.7,30.6,30.6,30.5,30.5
9,303910,MP 04: His & Hears,17/10/2022 02:00:00.000,35.7,35.2,32.4,31.5,31.2,31.0,30.8,30.7,30.6,30.5,30.5,30.4

In [ ]:
# Convert the 'result_timestamp' column to a datetime data type
file40['result_timestamp'] = pd.to_datetime(file40['result_timestamp'])
file40['date'] = file40['result_timestamp'].dt.date
file40['hour'] = file40['result_timestamp'].dt.hour
file40["month"] = file40["result_timestamp"].dt.month
file40['weekday'] = file40['result_timestamp'].dt.strftime('%a')
file40.head(4)

,object_id,location,result_timestamp,laf005_per_hour,laf01_per_hour,laf05_per_hour,laf10_per_hour,laf25_per_hour,laf50_per_hour,laf75_per_hour,laf90_per_hour,laf95_per_hour,laf98_per_hour,laf99_per_hour,laf995_per_hour,date,hour,month,weekday
0,303910,MP 04: His & Hears,2022-10-16 17:00:00,77.6,75.7,70.6,65.2,43.7,35.6,32.1,31.3,31.0,30.8,30.7,30.6,2022-10-16,17,10,Sun
1,303910,MP 04: His & Hears,2022-10-16 18:00:00,49.5,47.3,42.1,39.1,34.8,32.4,31.2,30.8,30.6,30.5,30.4,30.4,2022-10-16,18,10,Sun
2,303910,MP 04: His & Hears,2022-10-16 19:00:00,59.5,57.1,49.9,44.8,38.4,33.8,32.2,31.4,31.1,30.8,30.7,30.6,2022-10-16,19,10,Sun
3,303910,MP 04: His & Hears,2022-10-16 20:00:00,45.4,43.1,39.6,38.3,35.6,32.1,31.1,30.8,30.7,30.6,30.5,30.5,2022-10-16,20,10,Sun

In [ ]:
np.unique(file40.date)

array([datetime.date(2022, 1, 3), datetime.date(2022, 1, 4),
       datetime.date(2022, 1, 5), datetime.date(2022, 1, 6),
       datetime.date(2022, 1, 7), datetime.date(2022, 1, 8),
       datetime.date(2022, 1, 9), datetime.date(2022, 1, 10),
       datetime.date(2022, 1, 11), datetime.date(2022, 1, 12),
       datetime.date(2022, 2, 3), datetime.date(2022, 2, 4),
       datetime.date(2022, 2, 5), datetime.date(2022, 2, 6),
       datetime.date(2022, 2, 7), datetime.date(2022, 2, 8),
       datetime.date(2022, 2, 9), datetime.date(2022, 2, 10),
       datetime.date(2022, 2, 11), datetime.date(2022, 2, 12),
       datetime.date(2022, 2, 13), datetime.date(2022, 2, 14),
       datetime.date(2022, 2, 15), datetime.date(2022, 2, 16),
       datetime.date(2022, 2, 17), datetime.date(2022, 2, 18),
       datetime.date(2022, 2, 19), datetime.date(2022, 2, 20),
       datetime.date(2022, 2, 21), datetime.date(2022, 2, 22),
       datetime.date(2022, 2, 23), datetime.date(2022, 2, 24),
       datetime.date(2022, 2, 25), datetime.date(2022, 2, 26),
       datetime.date(2022, 2, 27), datetime.date(2022, 2, 28),
       datetime.date(2022, 3, 3), datetime.date(2022, 3, 4),
       datetime.date(2022, 3, 5), datetime.date(2022, 3, 6),
       datetime.date(2022, 3, 7), datetime.date(2022, 3, 8),
       datetime.date(2022, 3, 9), datetime.date(2022, 3, 10),
       datetime.date(2022, 3, 11), datetime.date(2022, 3, 12),
       datetime.date(2022, 3, 13), datetime.date(2022, 3, 14),
       datetime.date(2022, 3, 15), datetime.date(2022, 3, 16),
       datetime.date(2022, 3, 17), datetime.date(2022, 3, 18),
       datetime.date(2022, 3, 19), datetime.date(2022, 3, 20),
       datetime.date(2022, 3, 21), datetime.date(2022, 3, 22),
       datetime.date(2022, 3, 23), datetime.date(2022, 3, 24),
       datetime.date(2022, 3, 25), datetime.date(2022, 3, 26),
       datetime.date(2022, 3, 27), datetime.date(2022, 3, 28),
       datetime.date(2022, 3, 29), datetime.date(2022, 3, 30),
       datetime.date(2022, 3, 31), datetime.date(2022, 4, 3),
       datetime.date(2022, 4, 4), datetime.date(2022, 4, 5),
       datetime.date(2022, 4, 6), datetime.date(2022, 4, 7),
       datetime.date(2022, 4, 8), datetime.date(2022, 4, 9),
       datetime.date(2022, 4, 10), datetime.date(2022, 4, 11),
       datetime.date(2022, 4, 12), datetime.date(2022, 4, 13),
       datetime.date(2022, 4, 14), datetime.date(2022, 4, 15),
       datetime.date(2022, 4, 16), datetime.date(2022, 4, 17),
       datetime.date(2022, 4, 18), datetime.date(2022, 4, 19),
       datetime.date(2022, 4, 20), datetime.date(2022, 4, 21),
       datetime.date(2022, 4, 22), datetime.date(2022, 4, 23),
       datetime.date(2022, 4, 24), datetime.date(2022, 4, 25),
       datetime.date(2022, 4, 26), datetime.date(2022, 4, 27),
       datetime.date(2022, 4, 28), datetime.date(2022, 4, 29),
       datetime.date(2022, 4, 30), datetime.date(2022, 5, 3),
       datetime.date(2022, 5, 4), datetime.date(2022, 5, 5),
       datetime.date(2022, 5, 6), datetime.date(2022, 5, 7),
       datetime.date(2022, 5, 8), datetime.date(2022, 5, 9),
       datetime.date(2022, 5, 10), datetime.date(2022, 5, 11),
       datetime.date(2022, 5, 12), datetime.date(2022, 5, 13),
       datetime.date(2022, 5, 14), datetime.date(2022, 5, 15),
       datetime.date(2022, 5, 16), datetime.date(2022, 5, 17),
       datetime.date(2022, 5, 18), datetime.date(2022, 5, 19),
       datetime.date(2022, 5, 20), datetime.date(2022, 5, 21),
       datetime.date(2022, 5, 22), datetime.date(2022, 5, 23),
       datetime.date(2022, 5, 24), datetime.date(2022, 5, 25),
       datetime.date(2022, 5, 26), datetime.date(2022, 5, 27),
       datetime.date(2022, 5, 28), datetime.date(2022, 5, 29),
       datetime.date(2022, 5, 30), datetime.date(2022, 5, 31),
       datetime.date(2022, 6, 3), datetime.date(2022, 6, 4),
       datetime.date(2022, 6, 5), datetime.date(2022, 6, 6),
       datetime.date(2022, 6, 7), datetime.date(2022, 6, 8),
       datetime.date(2022, 6, 9), datetime.date(2022, 6, 10),
       datetime.date(2022, 6, 11), datetime.date(2022, 6, 12),
       datetime.date(2022, 6, 13), datetime.date(2022, 6, 14),
       datetime.date(2022, 6, 15), datetime.date(2022, 6, 16),
       datetime.date(2022, 6, 17), datetime.date(2022, 6, 18),
       datetime.date(2022, 6, 19), datetime.date(2022, 6, 20),
       datetime.date(2022, 6, 21), datetime.date(2022, 6, 22),
       datetime.date(2022, 6, 23), datetime.date(2022, 6, 24),
       datetime.date(2022, 6, 25), datetime.date(2022, 6, 26),
       datetime.date(2022, 6, 27), datetime.date(2022, 6, 28),
       datetime.date(2022, 6, 29), datetime.date(2022, 6, 30),
       datetime.date(2022, 7, 3), datetime.date(2022, 7, 4),
       datetime.date(2022, 7, 5), datetime.date(2022, 7, 6),
       datetime.date(2022, 7, 7), datetime.date(2022, 7, 8),
       datetime.date(2022, 7, 9), datetime.date(2022, 7, 10),
       datetime.date(2022, 7, 11), datetime.date(2022, 7, 12),
       datetime.date(2022, 7, 13), datetime.date(2022, 7, 14),
       datetime.date(2022, 7, 15), datetime.date(2022, 7, 16),
       datetime.date(2022, 7, 17), datetime.date(2022, 7, 18),
       datetime.date(2022, 7, 19), datetime.date(2022, 7, 20),
       datetime.date(2022, 7, 21), datetime.date(2022, 7, 22),
       datetime.date(2022, 7, 23), datetime.date(2022, 7, 24),
       datetime.date(2022, 7, 25), datetime.date(2022, 7, 26),
       datetime.date(2022, 7, 27), datetime.date(2022, 7, 28),
       datetime.date(2022, 7, 29), datetime.date(2022, 7, 30),
       datetime.date(2022, 7, 31), datetime.date(2022, 8, 2),
       datetime.date(2022, 8, 3), datetime.date(2022, 8, 4),
       datetime.date(2022, 8, 5), datetime.date(2022, 8, 6),
       datetime.date(2022, 8, 7), datetime.date(2022, 8, 8),
       datetime.date(2022, 8, 9), datetime.date(2022, 8, 10),
       datetime.date(2022, 8, 11), datetime.date(2022, 8, 12),
       datetime.date(2022, 8, 13), datetime.date(2022, 8, 14),
       datetime.date(2022, 8, 15), datetime.date(2022, 8, 16),
       datetime.date(2022, 8, 17), datetime.date(2022, 8, 18),
       datetime.date(2022, 8, 19), datetime.date(2022, 8, 20),
       datetime.date(2022, 8, 21), datetime.date(2022, 8, 22),
       datetime.date(2022, 8, 23), datetime.date(2022, 8, 24),
       datetime.date(2022, 8, 25), datetime.date(2022, 8, 26),
       datetime.date(2022, 8, 27), datetime.date(2022, 8, 28),
       datetime.date(2022, 8, 29), datetime.date(2022, 8, 30),
       datetime.date(2022, 8, 31), datetime.date(2022, 9, 2),
       datetime.date(2022, 9, 3), datetime.date(2022, 9, 4),
       datetime.date(2022, 9, 5), datetime.date(2022, 9, 6),
       datetime.date(2022, 9, 7), datetime.date(2022, 9, 8),
       datetime.date(2022, 9, 9), datetime.date(2022, 9, 10),
       datetime.date(2022, 9, 11), datetime.date(2022, 9, 12),
       datetime.date(2022, 9, 13), datetime.date(2022, 9, 14),
       datetime.date(2022, 9, 15), datetime.date(2022, 9, 16),
       datetime.date(2022, 9, 17), datetime.date(2022, 9, 18),
       datetime.date(2022, 9, 19), datetime.date(2022, 9, 20),
       datetime.date(2022, 9, 21), datetime.date(2022, 9, 22),
       datetime.date(2022, 9, 23), datetime.date(2022, 9, 24),
       datetime.date(2022, 9, 25), datetime.date(2022, 9, 26),
       datetime.date(2022, 9, 27), datetime.date(2022, 9, 28),
       datetime.date(2022, 9, 29), datetime.date(2022, 9, 30),
       datetime.date(2022, 10, 2), datetime.date(2022, 10, 3),
       datetime.date(2022, 10, 4), datetime.date(2022, 10, 5),
       datetime.date(2022, 10, 6), datetime.date(2022, 10, 7),
       datetime.date(2022, 10, 8), datetime.date(2022, 10, 9),
       datetime.date(2022, 10, 10), datetime.date(2022, 10, 11),
       datetime.date(2022, 10, 12), datetime.date(2022, 10, 13),
       datetime.date(2022, 10, 14), datetime.date(2022, 10, 15),
       datetime.date(2022, 10, 16), datetime.date(2022, 10, 17),
       datetime.date(2022, 10, 18), datetime.date(2022, 10, 19),
       datetime.date(2022, 10, 20), datetime.date(2022, 10, 21),
       datetime.date(2022, 10, 22), datetime.date(2022, 10, 23),
       datetime.date(2022, 10, 24), datetime.date(2022, 10, 25),
       datetime.date(2022, 10, 26), datetime.date(2022, 10, 27),
       datetime.date(2022, 10, 28), datetime.date(2022, 10, 29),
       datetime.date(2022, 10, 30), datetime.date(2022, 10, 31),
       datetime.date(2022, 11, 2), datetime.date(2022, 11, 3),
       datetime.date(2022, 11, 4), datetime.date(2022, 11, 5),
       datetime.date(2022, 11, 6), datetime.date(2022, 11, 7),
       datetime.date(2022, 11, 8), datetime.date(2022, 11, 9),
       datetime.date(2022, 11, 10), datetime.date(2022, 11, 11),
       datetime.date(2022, 11, 12), datetime.date(2022, 11, 13),
       datetime.date(2022, 11, 14), datetime.date(2022, 11, 15),
       datetime.date(2022, 11, 16), datetime.date(2022, 11, 17),
       datetime.date(2022, 11, 18), datetime.date(2022, 11, 19),
       datetime.date(2022, 11, 20), datetime.date(2022, 11, 21),
       datetime.date(2022, 11, 22), datetime.date(2022, 11, 23),
       datetime.date(2022, 11, 24), datetime.date(2022, 11, 25),
       datetime.date(2022, 11, 26), datetime.date(2022, 11, 27),
       datetime.date(2022, 11, 28), datetime.date(2022, 11, 29),
       datetime.date(2022, 11, 30), datetime.date(2022, 12, 2),
       datetime.date(2022, 12, 3), datetime.date(2022, 12, 4),
       datetime.date(2022, 12, 5), datetime.date(2022, 12, 6),
       datetime.date(2022, 12, 7), datetime.date(2022, 12, 8),
       datetime.date(2022, 12, 9), datetime.date(2022, 12, 10),
       datetime.date(2022, 12, 11), datetime.date(2022, 12, 12),
       datetime.date(2022, 12, 13), datetime.date(2022, 12, 14),
       datetime.date(2022, 12, 15), datetime.date(2022, 12, 16),
       datetime.date(2022, 12, 17), datetime.date(2022, 12, 18),
       datetime.date(2022, 12, 19), datetime.date(2022, 12, 20),
       datetime.date(2022, 12, 21), datetime.date(2022, 12, 22),
       datetime.date(2022, 12, 23), datetime.date(2022, 12, 24),
       datetime.date(2022, 12, 25), datetime.date(2022, 12, 26),
       datetime.date(2022, 12, 27), datetime.date(2022, 12, 28),
       datetime.date(2022, 12, 29), datetime.date(2022, 12, 30),
       datetime.date(2022, 12, 31)], dtype=object)

In [ ]:
np.unique(file40.object_id)

array([255439, 255440, 255441, 255442, 255443, 255444, 280324, 303910],
      dtype=object)

In [ ]:
file40.shape

(50320, 19)

## file 42 - noise level data

In [ ]:
file42.head(10)

,#object_id,description,result_timestamp,lamax,lamax_unit,laeq,laeq_unit,lceq,lceq_unit,lcpeak,lcpeak_unit
0,255441,MP 03: Naamsestraat 62 Taste,01/01/2022 00:00:00.349,87.6,dB(A),82.7,dB(A),83.61,dB(C),97.17,dB(C)
1,255441,MP 03: Naamsestraat 62 Taste,01/01/2022 00:00:01.349,84.5,dB(A),83.1,dB(A),84.42,dB(C),96.41,dB(C)
2,255441,MP 03: Naamsestraat 62 Taste,01/01/2022 00:00:02.349,84.8,dB(A),82.7,dB(A),84.19,dB(C),96.24,dB(C)
3,255441,MP 03: Naamsestraat 62 Taste,01/01/2022 00:00:03.349,81.9,dB(A),79.3,dB(A),81.08,dB(C),94.03,dB(C)
4,255441,MP 03: Naamsestraat 62 Taste,01/01/2022 00:00:04.349,78.3,dB(A),76.0,dB(A),77.12,dB(C),89.81,dB(C)
5,255441,MP 03: Naamsestraat 62 Taste,01/01/2022 00:00:05.349,80.5,dB(A),77.8,dB(A),78.91,dB(C),91.08,dB(C)
6,255441,MP 03: Naamsestraat 62 Taste,01/01/2022 00:00:06.350,78.4,dB(A),73.9,dB(A),75.87,dB(C),89.28,dB(C)
7,255441,MP 03: Naamsestraat 62 Taste,01/01/2022 00:00:07.350,70.1,dB(A),67.3,dB(A),70.17,dB(C),88.17,dB(C)
8,255441,MP 03: Naamsestraat 62 Taste,01/01/2022 00:00:08.350,65.1,dB(A),61.5,dB(A),64.78,dB(C),78.95,dB(C)
9,255441,MP 03: Naamsestraat 62 Taste,01/01/2022 00:00:09.350,73.7,dB(A),71.2,dB(A),73.62,dB(C),91.90,dB(C)

In [ ]:
file42.isna().mean()

#object_id          0.000000e+00
description         0.000000e+00
result_timestamp    0.000000e+00
lamax               2.812916e-07
lamax_unit          2.812916e-07
laeq                2.812916e-07
laeq_unit           2.812916e-07
lceq                1.125166e-06
lceq_unit           1.125166e-06
lcpeak              1.125166e-06
lcpeak_unit         1.125166e-06
dtype: float64

In [ ]:
file42.shape

(10665090, 11)

In [ ]:
# rename columns
file42.rename(columns={'description':'location',
                       "#object_id": "object_id"}, inplace=True)

In [ ]:
## remove obs that null
file42 = file42.loc[~file42.lamax.isnull(), ]
file42 = file42.loc[~file42.lceq.isnull(), ]

In [ ]:
file42.isna().mean()

object_id           0.0
location            0.0
result_timestamp    0.0
lamax               0.0
lamax_unit          0.0
laeq                0.0
laeq_unit           0.0
lceq                0.0
lceq_unit           0.0
lcpeak              0.0
lcpeak_unit         0.0
dtype: float64

In [ ]:
file42.shape

(10665075, 11)

In [ ]:
# Convert the 'result_timestamp' column to a datetime data type
file42['result_timestamp'] = pd.to_datetime(file42['result_timestamp'])
file42['date'] = file42['result_timestamp'].dt.date
file42['hour'] = file42['result_timestamp'].dt.hour
file42["month"] = file42["result_timestamp"].dt.month
file42['weekday'] = file42['result_timestamp'].dt.strftime('%a')
file42.head(4)

,object_id,location,result_timestamp,lamax,lamax_unit,laeq,laeq_unit,lceq,lceq_unit,lcpeak,lcpeak_unit,date,hour,month,weekday
0,255441,MP 03: Naamsestraat 62 Taste,2022-01-01 00:00:00.349,87.6,dB(A),82.7,dB(A),83.61,dB(C),97.17,dB(C),2022-01-01,0,1,Sat
1,255441,MP 03: Naamsestraat 62 Taste,2022-01-01 00:00:01.349,84.5,dB(A),83.1,dB(A),84.42,dB(C),96.41,dB(C),2022-01-01,0,1,Sat
2,255441,MP 03: Naamsestraat 62 Taste,2022-01-01 00:00:02.349,84.8,dB(A),82.7,dB(A),84.19,dB(C),96.24,dB(C),2022-01-01,0,1,Sat
3,255441,MP 03: Naamsestraat 62 Taste,2022-01-01 00:00:03.349,81.9,dB(A),79.3,dB(A),81.08,dB(C),94.03,dB(C),2022-01-01,0,1,Sat

In [ ]:
np.unique(file42.hour)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [ ]:
np.unique(file42.laeq_unit)

array(['dB(A)'], dtype=object)

In [ ]:
np.unique(file42.lamax_unit)

array(['dB(A)'], dtype=object)

In [ ]:
np.unique(file42.lceq_unit)

array(['dB(C)'], dtype=object)

In [ ]:
np.unique(file42.lcpeak_unit)

array(['dB(C)'], dtype=object)

In [ ]:
np.max(file40.date)

datetime.date(2022, 12, 31)

In [ ]:
np.min(file40.date)

datetime.date(2022, 1, 3)

In [ ]:
file42.drop(["lamax_unit", "laeq_unit",		"lceq_unit"	,	"lcpeak_unit"], inplace = True, axis  = 1)

## Meteo Data

In [ ]:
meteo = pd.concat([pd.read_csv("/content/drive/MyDrive/MDA_TIEN/LC_data/LC_2022Q1.csv", delimiter=","),
                  pd.read_csv("/content/drive/MyDrive/MDA_TIEN/LC_data/LC_2022Q2.csv", delimiter=","),
                  pd.read_csv("/content/drive/MyDrive/MDA_TIEN/LC_data/LC_2022Q3.csv", delimiter=","),
                  pd.read_csv("/content/drive/MyDrive/MDA_TIEN/LC_data/LC_2022Q4.csv", delimiter=",")])

In [ ]:
meteo.columns

Index(['DATEUTC', 'ID', 'LC_HUMIDITY', 'LC_DWPTEMP', 'LC_n', 'LC_RAD',
       'LC_RAININ', 'LC_DAILYRAIN', 'LC_WINDDIR', 'LC_WINDSPEED', 'Date',
       'Year', 'Month', 'Day', 'Hour', 'Minute', 'LC_RAD60', 'LC_TEMP_QCL0',
       'LC_TEMP_QCL1', 'LC_TEMP_QCL2', 'LC_TEMP_QCL3'],
      dtype='object')

In [ ]:
meteo.shape

(5546880, 21)

In [ ]:
meteo.head(4)

,DATEUTC,ID,LC_HUMIDITY,LC_DWPTEMP,LC_n,LC_RAD,LC_RAININ,LC_DAILYRAIN,LC_WINDDIR,LC_WINDSPEED,...,Year,Month,Day,Hour,Minute,LC_RAD60,LC_TEMP_QCL0,LC_TEMP_QCL1,LC_TEMP_QCL2,LC_TEMP_QCL3
0,2022-01-01 00:10:00,LC-002,92.0,11.78,38.0,0.0,0.0,0.0,-169.0,0.43,...,2022,1,1,0,10,0.0,13.11,13.11,13.0515,13.048027
1,2022-01-01 00:20:00,LC-002,92.0,11.73,37.0,0.0,0.0,0.0,-170.0,0.33,...,2022,1,1,0,20,0.0,13.01,13.01,12.9515,12.985849
2,2022-01-01 00:30:00,LC-002,92.0,11.73,38.0,0.0,0.0,0.0,-167.0,0.46,...,2022,1,1,0,30,0.0,13.00,13.00,12.9415,12.950322
3,2022-01-01 00:40:00,LC-002,92.0,11.72,37.0,0.0,0.0,0.0,-160.0,0.52,...,2022,1,1,0,40,0.0,13.00,13.00,12.9415,12.949550

In [ ]:
meteo.dtypes

DATEUTC         datetime64[ns]
ID                      object
LC_HUMIDITY            float64
LC_DWPTEMP             float64
LC_n                   float64
LC_RAD                 float64
LC_RAININ              float64
LC_DAILYRAIN           float64
LC_WINDDIR             float64
LC_WINDSPEED           float64
Date                    object
Year                     int64
Month                    int64
Day                      int64
Hour                     int64
Minute                   int64
LC_RAD60               float64
LC_TEMP_QCL0           float64
LC_TEMP_QCL1           float64
LC_TEMP_QCL2           float64
LC_TEMP_QCL3           float64
date                    object
hour                     int64
month                    int64
dtype: object

In [ ]:
meteo['weekday'] = meteo['DATEUTC'].dt.strftime('%a')

,DATEUTC,ID,LC_HUMIDITY,LC_DWPTEMP,LC_n,LC_RAD,LC_RAININ,LC_DAILYRAIN,LC_WINDDIR,LC_WINDSPEED,...,Minute,LC_RAD60,LC_TEMP_QCL0,LC_TEMP_QCL1,LC_TEMP_QCL2,LC_TEMP_QCL3,date,hour,month,weekday
0,2022-01-01 00:10:00,LC-002,92.0,11.78,38.0,0.0,0.0,0.0,-169.0,0.43,...,10,0.0,13.11,13.11,13.0515,13.048027,2022-01-01,0,1,Sat
1,2022-01-01 00:20:00,LC-002,92.0,11.73,37.0,0.0,0.0,0.0,-170.0,0.33,...,20,0.0,13.01,13.01,12.9515,12.985849,2022-01-01,0,1,Sat
2,2022-01-01 00:30:00,LC-002,92.0,11.73,38.0,0.0,0.0,0.0,-167.0,0.46,...,30,0.0,13.00,13.00,12.9415,12.950322,2022-01-01,0,1,Sat
3,2022-01-01 00:40:00,LC-002,92.0,11.72,37.0,0.0,0.0,0.0,-160.0,0.52,...,40,0.0,13.00,13.00,12.9415,12.949550,2022-01-01,0,1,Sat

In [ ]:
meteo.head(4)

,DATEUTC,ID,LC_HUMIDITY,LC_DWPTEMP,LC_n,LC_RAD,LC_RAININ,LC_DAILYRAIN,LC_WINDDIR,LC_WINDSPEED,...,Month,Day,Hour,Minute,LC_RAD60,LC_TEMP_QCL0,LC_TEMP_QCL1,LC_TEMP_QCL2,LC_TEMP_QCL3,weekday
0,2022-01-01 00:10:00,LC-002,92.0,11.78,38.0,0.0,0.0,0.0,-169.0,0.43,...,1,1,0,10,0.0,13.11,13.11,13.0515,13.048027,Sat
1,2022-01-01 00:20:00,LC-002,92.0,11.73,37.0,0.0,0.0,0.0,-170.0,0.33,...,1,1,0,20,0.0,13.01,13.01,12.9515,12.985849,Sat
2,2022-01-01 00:30:00,LC-002,92.0,11.73,38.0,0.0,0.0,0.0,-167.0,0.46,...,1,1,0,30,0.0,13.00,13.00,12.9415,12.950322,Sat
3,2022-01-01 00:40:00,LC-002,92.0,11.72,37.0,0.0,0.0,0.0,-160.0,0.52,...,1,1,0,40,0.0,13.00,13.00,12.9415,12.949550,Sat

In [ ]:
meteo.isna().mean()

DATEUTC         0.000000
ID              0.000000
LC_HUMIDITY     0.056770
LC_DWPTEMP      0.056770
LC_n            0.056770
LC_RAD          0.056770
LC_RAININ       0.056770
LC_DAILYRAIN    0.056770
LC_WINDDIR      0.056770
LC_WINDSPEED    0.056770
Date            0.000000
Year            0.000000
Month           0.000000
Day             0.000000
Hour            0.000000
Minute          0.000000
LC_RAD60        0.049942
LC_TEMP_QCL0    0.056770
LC_TEMP_QCL1    0.062285
LC_TEMP_QCL2    0.062285
LC_TEMP_QCL3    0.062285
weekday         0.000000
dtype: float64

In [ ]:
meteo['date'] = meteo['DATEUTC'].dt.date

In [ ]:
meteo = meteo[~meteo.LC_HUMIDITY.isnull()]

In [ ]:
meteo.isna().mean()

DATEUTC         0.000000
ID              0.000000
LC_HUMIDITY     0.000000
LC_DWPTEMP      0.000000
LC_n            0.000000
LC_RAD          0.000000
LC_RAININ       0.000000
LC_DAILYRAIN    0.000000
LC_WINDDIR      0.000000
LC_WINDSPEED    0.000000
Date            0.000000
Year            0.000000
Month           0.000000
Day             0.000000
Hour            0.000000
Minute          0.000000
LC_RAD60        0.000000
LC_TEMP_QCL0    0.000000
LC_TEMP_QCL1    0.005846
LC_TEMP_QCL2    0.005846
LC_TEMP_QCL3    0.005846
weekday         0.000000
dtype: float64

## Data processing

In [ ]:
file40.head(4)

,object_id,location,result_timestamp,laf005_per_hour,laf01_per_hour,laf05_per_hour,laf10_per_hour,laf25_per_hour,laf50_per_hour,laf75_per_hour,laf90_per_hour,laf95_per_hour,laf98_per_hour,laf99_per_hour,laf995_per_hour,date,hour,month,weekday
0,303910,MP 04: His & Hears,2022-10-16 17:00:00,77.6,75.7,70.6,65.2,43.7,35.6,32.1,31.3,31.0,30.8,30.7,30.6,2022-10-16,17,10,Sun
1,303910,MP 04: His & Hears,2022-10-16 18:00:00,49.5,47.3,42.1,39.1,34.8,32.4,31.2,30.8,30.6,30.5,30.4,30.4,2022-10-16,18,10,Sun
2,303910,MP 04: His & Hears,2022-10-16 19:00:00,59.5,57.1,49.9,44.8,38.4,33.8,32.2,31.4,31.1,30.8,30.7,30.6,2022-10-16,19,10,Sun
3,303910,MP 04: His & Hears,2022-10-16 20:00:00,45.4,43.1,39.6,38.3,35.6,32.1,31.1,30.8,30.7,30.6,30.5,30.5,2022-10-16,20,10,Sun

In [ ]:
file40 = file40.groupby(["object_id", "date", "hour", "month", "weekday"]).mean().reset_index()

In [ ]:
file40.head(4)

,object_id,date,hour,month,weekday,laf005_per_hour,laf01_per_hour,laf05_per_hour,laf10_per_hour,laf25_per_hour,laf50_per_hour,laf75_per_hour,laf90_per_hour,laf95_per_hour,laf98_per_hour,laf99_per_hour,laf995_per_hour
0,255439,2022-01-04,0,1,Tue,77.2,75.4,70.8,68.9,66.0,62.8,60.1,58.0,56.9,55.9,55.1,54.5
1,255439,2022-01-04,1,1,Tue,78.8,77.2,73.6,72.1,69.8,67.6,65.4,63.5,62.4,61.1,60.4,59.7
2,255439,2022-01-04,2,1,Tue,79.7,77.2,72.5,70.8,68.6,66.2,64.0,62.1,60.9,59.8,59.0,58.3
3,255439,2022-01-04,3,1,Tue,75.0,73.6,69.8,68.1,65.9,63.7,61.6,59.8,58.8,57.8,57.1,56.5

In [ ]:
file40.shape

(50314, 17)

In [ ]:
file41.head(4)

,object_id,location,result_timestamp,noise_event_certainty,noise_event,time,date,hour,month,weekday
94,255440,MP 02: Naamsestraat 57 Xior,2022-07-03 22:22:41.166,75.0,Transport road - Passenger car,22:22:41.166000,2022-07-03,22,7,Sun
95,255440,MP 02: Naamsestraat 57 Xior,2022-08-03 01:25:51.161,75.0,Transport road - Siren,01:25:51.161000,2022-08-03,1,8,Wed
96,255440,MP 02: Naamsestraat 57 Xior,2022-08-03 07:20:38.135,98.0,Transport road - Passenger car,07:20:38.135000,2022-08-03,7,8,Wed
97,255440,MP 02: Naamsestraat 57 Xior,2022-08-03 08:37:44.126,81.0,Transport road - Passenger car,08:37:44.126000,2022-08-03,8,8,Wed

In [ ]:
file41 = pd.pivot_table(file41, index = ["object_id", "date", "hour", "month", "weekday"], columns=["noise_event"], aggfunc='count').xs("location", level=0, axis=1).reset_index()

In [ ]:
file41.head(4)

noise_event,object_id,date,hour,month,weekday,Human voice - Shouting,Human voice - Singing,Music non-amplified,Nature elements - Wind,Transport road - Passenger car,Transport road - Siren
0,255439,2022-01-04,0,1,Tue,4.0,NaN,NaN,NaN,NaN,1.0
1,255439,2022-01-04,1,1,Tue,10.0,NaN,NaN,NaN,NaN,NaN
2,255439,2022-01-04,2,1,Tue,8.0,NaN,NaN,NaN,NaN,NaN
3,255439,2022-01-04,3,1,Tue,6.0,NaN,NaN,NaN,NaN,NaN

In [ ]:
file41.fillna(0, inplace=True)

In [ ]:
file41.head(4)

noise_event,object_id,date,hour,month,weekday,Human voice - Shouting,Human voice - Singing,Music non-amplified,Nature elements - Wind,Transport road - Passenger car,Transport road - Siren
0,255439,2022-01-04,0,1,Tue,4.0,0.0,0.0,0.0,0.0,1.0
1,255439,2022-01-04,1,1,Tue,10.0,0.0,0.0,0.0,0.0,0.0
2,255439,2022-01-04,2,1,Tue,8.0,0.0,0.0,0.0,0.0,0.0
3,255439,2022-01-04,3,1,Tue,6.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
file42.head(4)

,object_id,location,result_timestamp,lamax,laeq,lceq,lcpeak,date,hour,month,weekday
0,255441,MP 03: Naamsestraat 62 Taste,2022-01-01 00:00:00.349,87.6,82.7,83.61,97.17,2022-01-01,0,1,Sat
1,255441,MP 03: Naamsestraat 62 Taste,2022-01-01 00:00:01.349,84.5,83.1,84.42,96.41,2022-01-01,0,1,Sat
2,255441,MP 03: Naamsestraat 62 Taste,2022-01-01 00:00:02.349,84.8,82.7,84.19,96.24,2022-01-01,0,1,Sat
3,255441,MP 03: Naamsestraat 62 Taste,2022-01-01 00:00:03.349,81.9,79.3,81.08,94.03,2022-01-01,0,1,Sat

In [ ]:
file42 = file42.groupby(["object_id", "date", "hour", "month", "weekday"]).mean().reset_index()

<ipython-input-162-a3251ca185f7>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  file42 = file42.groupby(["object_id", "date", "hour", "month", "weekday"]).mean().reset_index()

In [ ]:
file42.head(4)

,object_id,date,hour,month,weekday,lamax,laeq,lceq,lcpeak
0,255441,2022-01-01,0,1,Sat,60.322528,57.126833,63.104650,76.595981
1,255441,2022-01-01,1,1,Sat,53.033583,50.853806,58.648786,71.017533
2,255441,2022-01-01,2,1,Sat,52.173702,50.049903,58.282633,70.640550
3,255441,2022-01-01,3,1,Sat,50.821311,48.964907,57.793745,69.698255

In [ ]:
file42.shape

(2964, 9)

In [ ]:
np.unique(k.date)

array([datetime.date(2022, 1, 1), datetime.date(2022, 1, 13),
       datetime.date(2022, 1, 14), datetime.date(2022, 1, 15),
       datetime.date(2022, 1, 16), datetime.date(2022, 1, 17),
       datetime.date(2022, 1, 18), datetime.date(2022, 1, 19),
       datetime.date(2022, 1, 20), datetime.date(2022, 1, 21),
       datetime.date(2022, 1, 22), datetime.date(2022, 1, 23),
       datetime.date(2022, 1, 24), datetime.date(2022, 1, 25),
       datetime.date(2022, 1, 26), datetime.date(2022, 1, 27),
       datetime.date(2022, 1, 28), datetime.date(2022, 1, 29),
       datetime.date(2022, 1, 30), datetime.date(2022, 1, 31),
       datetime.date(2022, 2, 1), datetime.date(2022, 3, 1),
       datetime.date(2022, 4, 1), datetime.date(2022, 5, 1),
       datetime.date(2022, 6, 1), datetime.date(2022, 7, 1),
       datetime.date(2022, 8, 1), datetime.date(2022, 9, 1),
       datetime.date(2022, 10, 1), datetime.date(2022, 11, 1),
       datetime.date(2022, 12, 1)], dtype=object)

In [ ]:
meteo.shape

(5231981, 23)

In [ ]:
meteo.head(2)

,DATEUTC,ID,LC_HUMIDITY,LC_DWPTEMP,LC_n,LC_RAD,LC_RAININ,LC_DAILYRAIN,LC_WINDDIR,LC_WINDSPEED,...,Day,Hour,Minute,LC_RAD60,LC_TEMP_QCL0,LC_TEMP_QCL1,LC_TEMP_QCL2,LC_TEMP_QCL3,weekday,date
0,2022-01-01 00:10:00,LC-002,92.0,11.78,38.0,0.0,0.0,0.0,-169.0,0.43,...,1,0,10,0.0,13.11,13.11,13.0515,13.048027,Sat,2022-01-01
1,2022-01-01 00:20:00,LC-002,92.0,11.73,37.0,0.0,0.0,0.0,-170.0,0.33,...,1,0,20,0.0,13.01,13.01,12.9515,12.985849,Sat,2022-01-01

In [ ]:
meteo.columns

Index(['DATEUTC', 'ID', 'LC_HUMIDITY', 'LC_DWPTEMP', 'LC_n', 'LC_RAD',
       'LC_RAININ', 'LC_DAILYRAIN', 'LC_WINDDIR', 'LC_WINDSPEED', 'Date',
       'Year', 'Month', 'Day', 'Hour', 'Minute', 'LC_RAD60', 'LC_TEMP_QCL0',
       'LC_TEMP_QCL1', 'LC_TEMP_QCL2', 'LC_TEMP_QCL3', 'weekday', 'date'],
      dtype='object')

In [ ]:
meteo = meteo.groupby(["date", "weekday", "Month", "Hour"]).mean().reset_index()

<ipython-input-172-2436f4388734>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  meteo = meteo.groupby(["date", "weekday", "Month", "Hour"]).mean().reset_index()

In [ ]:
meteo.drop(["Year", "Day", "Minute"], axis = 1, inplace = True)

In [ ]:
meteo.head(4)

,date,weekday,Month,Hour,LC_HUMIDITY,LC_DWPTEMP,LC_n,LC_RAD,LC_RAININ,LC_DAILYRAIN,LC_WINDDIR,LC_WINDSPEED,LC_RAD60,LC_TEMP_QCL0,LC_TEMP_QCL1,LC_TEMP_QCL2,LC_TEMP_QCL3
0,2022-01-01,Sat,1,0,90.367865,11.501860,36.353066,0.082452,0.000000,0.0,-17.124736,0.153679,0.082452,13.043446,13.054252,13.039616,13.013112
1,2022-01-01,Sat,1,1,89.504394,11.350650,36.316344,0.093146,0.000007,0.0,-17.166960,0.229297,0.084359,13.032021,13.042771,13.028941,13.022762
2,2022-01-01,Sat,1,2,89.311072,11.132355,36.525483,0.094903,0.000009,0.0,-14.453427,0.224025,0.093146,12.837575,12.850302,12.836191,12.828541
3,2022-01-01,Sat,1,3,89.400000,10.985421,36.463158,0.085965,0.000000,0.0,-17.203509,0.183456,0.092982,12.674368,12.686330,12.671846,12.688939

## combine data

In [ ]:
file40.head(4)

,object_id,date,hour,month,weekday,laf005_per_hour,laf01_per_hour,laf05_per_hour,laf10_per_hour,laf25_per_hour,laf50_per_hour,laf75_per_hour,laf90_per_hour,laf95_per_hour,laf98_per_hour,laf99_per_hour,laf995_per_hour
0,255439,2022-01-04,0,1,Tue,77.2,75.4,70.8,68.9,66.0,62.8,60.1,58.0,56.9,55.9,55.1,54.5
1,255439,2022-01-04,1,1,Tue,78.8,77.2,73.6,72.1,69.8,67.6,65.4,63.5,62.4,61.1,60.4,59.7
2,255439,2022-01-04,2,1,Tue,79.7,77.2,72.5,70.8,68.6,66.2,64.0,62.1,60.9,59.8,59.0,58.3
3,255439,2022-01-04,3,1,Tue,75.0,73.6,69.8,68.1,65.9,63.7,61.6,59.8,58.8,57.8,57.1,56.5

In [ ]:
file41.head(4)

noise_event,object_id,date,hour,month,weekday,Human voice - Shouting,Human voice - Singing,Music non-amplified,Nature elements - Wind,Transport road - Passenger car,Transport road - Siren
0,255439,2022-01-04,0,1,Tue,4.0,0.0,0.0,0.0,0.0,1.0
1,255439,2022-01-04,1,1,Tue,10.0,0.0,0.0,0.0,0.0,0.0
2,255439,2022-01-04,2,1,Tue,8.0,0.0,0.0,0.0,0.0,0.0
3,255439,2022-01-04,3,1,Tue,6.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
file41 = file41.rename(columns={'Human voice - Shouting': 'HM_voice_shout',
                        'Human voice - Singing': 'HM_voice_sing',
                        'Music non-amplified': 'MS_non_amplified',
                        'Nature elements - Wind': 'NE_wind',
                        'Transport road - Passenger car': 'TR_passenger_car',
                        'Transport road - Siren': 'TR_siren'})

In [ ]:
file41.head(4)

noise_event,object_id,date,hour,month,weekday,HM_voice_shout,HM_voice_sing,MS_non_amplified,NE_wind,TR_passenger_car,TR_siren
0,255439,2022-01-04,0,1,Tue,4.0,0.0,0.0,0.0,0.0,1.0
1,255439,2022-01-04,1,1,Tue,10.0,0.0,0.0,0.0,0.0,0.0
2,255439,2022-01-04,2,1,Tue,8.0,0.0,0.0,0.0,0.0,0.0
3,255439,2022-01-04,3,1,Tue,6.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
file41.shape

(20692, 11)

In [ ]:
file40.shape

(50314, 17)

In [ ]:
np.unique(file41.object_id)

array([255439, 255440, 255441, 255442, 255443, 255444, 280324])

In [ ]:
np.unique(file40.object_id)

array([255439, 255440, 255441, 255442, 255443, 255444, 280324, 303910])

In [ ]:
data_model = file40.merge(file41, how = "inner",
                          left_on = ["object_id", "date", "hour", "month", "weekday"],
                          right_on = ["object_id", "date", "hour", "month", "weekday"])

In [ ]:
data_model.shape

(20414, 23)

In [ ]:
data_model.columns

Index(['object_id', 'date', 'hour', 'month', 'weekday', 'laf005_per_hour',
       'laf01_per_hour', 'laf05_per_hour', 'laf10_per_hour', 'laf25_per_hour',
       'laf50_per_hour', 'laf75_per_hour', 'laf90_per_hour', 'laf95_per_hour',
       'laf98_per_hour', 'laf99_per_hour', 'laf995_per_hour', 'HM_voice_shout',
       'HM_voice_sing', 'MS_non_amplified', 'NE_wind', 'TR_passenger_car',
       'TR_siren'],
      dtype='object')

In [ ]:
data_model.head(3)

,object_id,date,hour,month,weekday,laf005_per_hour,laf01_per_hour,laf05_per_hour,laf10_per_hour,laf25_per_hour,...,laf95_per_hour,laf98_per_hour,laf99_per_hour,laf995_per_hour,HM_voice_shout,HM_voice_sing,MS_non_amplified,NE_wind,TR_passenger_car,TR_siren
0,255439,2022-01-04,0,1,Tue,77.2,75.4,70.8,68.9,66.0,...,56.9,55.9,55.1,54.5,4.0,0.0,0.0,0.0,0.0,1.0
1,255439,2022-01-04,1,1,Tue,78.8,77.2,73.6,72.1,69.8,...,62.4,61.1,60.4,59.7,10.0,0.0,0.0,0.0,0.0,0.0
2,255439,2022-01-04,2,1,Tue,79.7,77.2,72.5,70.8,68.6,...,60.9,59.8,59.0,58.3,8.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
meteo.head(2)

,date,weekday,Month,Hour,LC_HUMIDITY,LC_DWPTEMP,LC_n,LC_RAD,LC_RAININ,LC_DAILYRAIN,LC_WINDDIR,LC_WINDSPEED,LC_RAD60,LC_TEMP_QCL0,LC_TEMP_QCL1,LC_TEMP_QCL2,LC_TEMP_QCL3
0,2022-01-01,Sat,1,0,90.367865,11.50186,36.353066,0.082452,0.000000,0.0,-17.124736,0.153679,0.082452,13.043446,13.054252,13.039616,13.013112
1,2022-01-01,Sat,1,1,89.504394,11.35065,36.316344,0.093146,0.000007,0.0,-17.166960,0.229297,0.084359,13.032021,13.042771,13.028941,13.022762

In [ ]:
meteo.shape

(8761, 17)

In [ ]:
data_model = data_model.merge(meteo, how = "inner",
                              left_on = ["date", "hour", "month", "weekday"],
                              right_on = ["date", "Hour", "Month", "weekday"])

In [ ]:
data_model.columns

Index(['object_id', 'date', 'hour', 'month', 'weekday', 'laf005_per_hour',
       'laf01_per_hour', 'laf05_per_hour', 'laf10_per_hour', 'laf25_per_hour',
       'laf50_per_hour', 'laf75_per_hour', 'laf90_per_hour', 'laf95_per_hour',
       'laf98_per_hour', 'laf99_per_hour', 'laf995_per_hour', 'HM_voice_shout',
       'HM_voice_sing', 'MS_non_amplified', 'NE_wind', 'TR_passenger_car',
       'TR_siren', 'Month', 'Hour', 'LC_HUMIDITY', 'LC_DWPTEMP', 'LC_n',
       'LC_RAD', 'LC_RAININ', 'LC_DAILYRAIN', 'LC_WINDDIR', 'LC_WINDSPEED',
       'LC_RAD60', 'LC_TEMP_QCL0', 'LC_TEMP_QCL1', 'LC_TEMP_QCL2',
       'LC_TEMP_QCL3'],
      dtype='object')

In [ ]:
data_model.shape

(20414, 38)

In [ ]:
data_model.dtypes

object_id             int64
date                 object
hour                  int64
month                 int64
weekday              object
laf005_per_hour     float64
laf01_per_hour      float64
laf05_per_hour      float64
laf10_per_hour      float64
laf25_per_hour      float64
laf50_per_hour      float64
laf75_per_hour      float64
laf90_per_hour      float64
laf95_per_hour      float64
laf98_per_hour      float64
laf99_per_hour      float64
laf995_per_hour     float64
HM_voice_shout      float64
HM_voice_sing       float64
MS_non_amplified    float64
NE_wind             float64
TR_passenger_car    float64
TR_siren            float64
Month                 int64
Hour                  int64
LC_HUMIDITY         float64
LC_DWPTEMP          float64
LC_n                float64
LC_RAD              float64
LC_RAININ           float64
LC_DAILYRAIN        float64
LC_WINDDIR          float64
LC_WINDSPEED        float64
LC_RAD60            float64
LC_TEMP_QCL0        float64
LC_TEMP_QCL1        float64
LC_TEMP_QCL2        float64
LC_TEMP_QCL3        float64
dtype: object

In [ ]:
data_model.to_csv('/content/drive/MyDrive/MDA_TIEN/data_model.csv', index=False)